name: Testing and pushing to docker registry

on: [workflow_dispatch]

env:
  VPS_ROOT_PASSWORD: ${{ secrets.VPS_ROOT_PASSWORD }}
  VPS_SSH: ${{ secrets.VPS_SSH }}
  VPS_HOST: ${{ secrets.VPS_HOST }}
  VPS_USER: ${{ secrets.VPS_USER }}

jobs:
  deploy:
    name: deploy application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.VPS_HOST }}
          password: ${{ env.VPS_ROOT_PASSWORD }}
          username: ${{ env.VPS_USER }}
          run: |
            echo "login to vps success"

      - name: install depen
        run: npm i

      - name: build app
        run: npm run build
      - name: check the dist directory if exist or not
        run: ls -a

      - name: copy dist directory to the vps (if already exist then delete and put new one)
        uses: appleboy/scp-action@v1
        with:
          host: ${{ env.VPS_HOST }}
          password: ${{ env.VPS_ROOT_PASSWORD }}
          username: ${{ env.VPS_USER }}
          source: './dist'
          target: '~/workspace/nest-app'
          rm: false
          run: |
            ls -a
            echo "dist copied successfully"

      - name: Run git pull & npm install on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.VPS_HOST }}
          password: ${{ env.VPS_ROOT_PASSWORD }}
          username: ${{ env.VPS_USER }}
          script_path: ./script.sh
